name: Pt connections
favicon: null
layout_spectrum: 0.3100631863344461
typography_spectrum: 0.6297774468548596
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.9465979656670243
  lightness: 0.2673761770129204
  saturation: 0.8423992483876646
  rhythmicContrast: 0.40074015129357576
purpose: []
